### ISSUE TITLE
Error when trying to run any IDL command 

### ISSUE THREAD

**Issue by samaloney** [wtbarnes/hissw#38]
```
import hissw
ssw = hissw.Environment()
ssw.run('dindgen(10)')
/urs/local/ssw/gen/setup/setup.ssw: No such file or directory.


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sm/.virtualenvs/stixpy/lib/python3.11/site-packages/hissw/environment.py", line 186, in run
    results = readsav(save_filename)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sm/.virtualenvs/stixpy/lib/python3.11/site-packages/scipy/io/_idl.py", line 752, in readsav
    f = open(file_name, 'rb')
        ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/h1/wy_cdhsj1c9_9pr0x9shjrcr0000gp/T/tmpdvs0lsx2/idl_vars_20240612-223603.sav'
```

### Details
hisswrc
```
[hissw]
ssw_home=/urs/local/ssw
idl_home=/Applications/NV5/idl/bin
```

hissw 2.3
Python 3.11.7
IDL 9.0.0 (darwin arm64 m64)

**Comment by wtbarnes** [comment]
Were running this in a Jupyter notebook? Could this be related to #37?

**Comment by samaloney** [comment]
Hum it was a long time ago I'm afraid I don't remember but I think I would have noted that I can try to the env I was using verify it was a python script/shell

**Comment by samaloney** [comment]
No so not in Jupyter just did a clean setup python 3.12.9 and hissw 2.3 same error. It looks as if the temp sav file is not being created or is being removed/deleted too soon?


```
Python 3.12.9 (main, Jul 31 2025, 21:38:37) [Clang 17.0.0 (clang-1700.0.13.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hissw
>>> ssw = hissw.Environment()
>>> ssw
<hissw.environment.Environment object at 0x1008128a0>
>>> ssw.run('dindgen(10)')
/urs/local/ssw/gen/setup/setup.ssw: No such file or directory.


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sm/.virtualenvs/sunkit-spex/lib/python3.12/site-packages/hissw/environment.py", line 186, in run
    results = readsav(save_filename)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sm/.virtualenvs/sunkit-spex/lib/python3.12/site-packages/scipy/io/_idl.py", line 754, in readsav
    f = open(file_name, 'rb')
        ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/h1/wy_cdhsj1c9_9pr0x9shjrcr0000gp/T/tmpm8oywqll/idl_vars_20250801-100311.sav'
>>>
KeyboardInterrupt
>>>

#ls /var/folders/h1/wy_cdhsj1c9_9pr0x9shjrcr0000gp/T/tmpm8oywqll                                                                                                                                  
ls: /var/folders/h1/wy_cdhsj1c9_9pr0x9shjrcr0000gp/T/tmpm8oywqll: No such file or directory
```

**Comment by samaloney** [comment]
Ok sometimes I really do think I have some dyslexia like condition `/usr/local/ssw` != `/urs/local/ssw`, so user error.

It might be useful to raise an error if the expected file/s, path/s don't exist when creating the `Environment`?

**Comment by wtbarnes** [comment]
Ha I didn't even catch that! Yes some sort of path checking would be a good idea, maybe with some setter logic.
